
services:
  backend:
    build: ./backend
    environment:
      - FILE_STORAGE=/app/uploads
      - DB_PATH=sqlite:///./data.db
    ports:
      - "8080:8988"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    restart: always
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8989"
    depends_on:
      - backend
    restart: always
