services:
  backend:
    build:
      context: ./backend
    pull_policy: build
    environment:
      - FILE_STORAGE=/app/uploads
      - DB_PATH=/app/data/data.db
      - WEBUI_URL=${BASE_URL}:${WWW_PORT}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    restart: always
  frontend:
    build:
      context: ./frontend
      args: REACT_APP_API=${BASE_URL}:${API_PORT}
        REACT_APP_TAG=${SEMVER}
    pull_policy: build
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "${WWW_PORT}:5173"
    depends_on:
      - backend
    restart: always
volumes:
  node_modules:
env_file:
  - stack.env
