
services:
  backend:
    build: 
      context: ./backend
    pull_policy: build
    environment:
      - FILE_STORAGE=/app/uploads
      - DB_PATH=data.db
    ports:
      - "8988:8080"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    restart: always
  frontend:
    build:
      context: ./frontend
    pull_policy: build
    volumes:
      - node_modules:/app/www/node_modules
    ports:
      - "8989:8081"
    depends_on:
      - backend
    restart: always
volumes:
  node_modules:
