name: Bump Docker Semver

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run:
    if: github.event.pull_request.merged == true
    name: Bump stack version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Get next version
        uses: reecetech/version-increment@2024.10.1
        id: version
        with:
          scheme: conventional_commits
      
      - name: Find and Replace
        uses: thiagodnf/string-replacer@v1.0.2
        with:
          find: 'SEMVER=.+'
          replace: 'SEMVER=${{ steps.version.outputs.version }}'
          include: |
            stack.env
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: ${{ github.event.pull_request.title }}
          add: 'stack.env'
